=== ckaestne/CIDE/CIDE_Samples/cide_samples/MobileMedia08/annotations.dtd
<!ELEMENT project (feature|folder|file)*>
<!ATTLIST project   name   CDATA    #REQUIRED >
<!ELEMENT folder (feature|folder|file)*>
<!ATTLIST folder name   CDATA    #REQUIRED >
<!ELEMENT file (feature|fragment)*>
<!ATTLIST file  name   CDATA    #REQUIRED >
<!ELEMENT fragment (feature)*>
<!ATTLIST fragment  offset   CDATA    #REQUIRED  length   CDATA    #REQUIRED >
<!ELEMENT feature (#PCDATA)>

=== ckaestne/CIDE/CIDE_Samples/cide_samples/MobileMedia08/annotations.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE project SYSTEM "annotations.dtd">
<project name="MobileMedia08_OO">
	<file name=".classpath" />
	<folder name=".eclipseme.tmp">
		<folder name="emulation">
			<file name="MobileMedia07_OO.jad" />
			<file name="MobileMedia07_OO.jar" />
			<file name="MobileMedia08_OO.jad" />
			<file name="MobileMedia08_OO.jar" />
		</folder>
	</folder>
	<file name=".project" />
	<file name="MobileMediaCompileList.lst" />
	<file name="annotations.xml" />
	<folder name="bin">
		<file name="LocMetrics.css" />
		<file name="LocMetrics.html" />
		<file name="LocMetricsCommentWords.csv" />
		<file name="LocMetricsFiles.csv" />
		<file name="LocMetricsFolders.csv" />
		<file name="LocMetricsPie.jpg" />
		<file name="LocMetricsPie.png" />
		<folder name="lancs">
			<folder name="mobilemedia">
				<folder name="core">
					<folder name="comms">
						<file name="BaseMessaging.class" />
					</folder>
					<folder name="threads">
						<file name="BaseThread.class" />
					</folder>
					<folder name="ui">
						<file name="MainUIMidlet.class" />
						<file name="MainUIMidlet.java.color" />
						<folder name="controller">
							<file name=".dircolors" />
							<file name="AbstractController.class" />
							<file name="AlbumController.class" />
							<file name="AlbumController.java.color" />
							<file name="BaseController.class" />
							<file name="BaseController.java.color" />
							<file name="ControllerInterface.class" />
							<file name="MediaController.class" />
							<file name="MediaController.java.color" />
							<file name="MediaListController.class" />
							<file name="MediaListController.java.color" />
							<file name="MusicPlayController.class" />
							<file name="MusicPlayController.java.color" />
							<file name="PhotoViewController.class" />
							<file name="PhotoViewController.java.color" />
							<file name="PlayVideoController.class" />
							<file name="PlayVideoController.java.color" />
							<file name="ScreenSingleton.class" />
							<file name="ScreenSingleton.java.color" />
							<file name="SelectMediaController.class" />
							<file name="SelectMediaController.java.color" />
							<file name="VideoCaptureController.class" />
							<file name="VideoCaptureController.java.color" />
						</folder>
						<folder name="datamodel">
							<file name=".dircolors" />
							<file name="AlbumData.class" />
							<file name="AlbumData.java.color" />
							<file name="ImageAlbumData.class" />
							<file name="ImageAlbumData.java.color" />
							<file name="ImageMediaAccessor.class" />
							<file name="ImageMediaAccessor.java.color" />
							<file name="MediaAccessor.class" />
							<file name="MediaAccessor.java.color" />
							<file name="MediaData.class" />
							<file name="MediaData.java.color" />
							<file name="MusicAlbumData.class" />
							<file name="MusicAlbumData.java.color" />
							<file name="MusicMediaAccessor.class" />
							<file name="MusicMediaAccessor.java.color" />
							<file name="VideoAlbumData.class" />
							<file name="VideoAlbumData.java.color" />
							<file name="VideoMediaAccessor.class" />
							<file name="VideoMediaAccessor.java.color" />
						</folder>
						<folder name="screens">
							<file name=".cvsignore" />
							<file name=".dircolors" />
							<file name="AddMediaToAlbum.class" />
							<file name="AddMediaToAlbum.java.color" />
							<file name="AlbumListScreen.class" />
							<file name="AlbumListScreen.java.color" />
							<file name="CaptureVideoScreen.class" />
							<file name="CaptureVideoScreen.java.color" />
							<file name="MediaListScreen.class" />
							<file name="MediaListScreen.java.color" />
							<file name="NewLabelScreen.class" />
							<file name="NewLabelScreen.java.color" />
							<file name="PasswordScreen.class" />
							<file name="PasswordScreen.java.color" />
							<file name="PhotoViewScreen.class" />
							<file name="PhotoViewScreen.java.color" />
							<file name="PlayMediaScreen.class" />
							<file name="PlayMediaScreen.java.color" />
							<file name="PlayVideoScreen.class" />
							<file name="PlayVideoScreen.java.color" />
							<file name="SelectTypeOfMedia.class" />
							<file name="SelectTypeOfMedia.java.color" />
						</folder>
					</folder>
					<folder name="util">
						<file name=".dircolors" />
						<file name="Constants.class" />
						<file name="Constants.java.color" />
						<file name="MediaUtil.class" />
						<file name="MediaUtil.java.color" />
						<file name="MusicMediaUtil.class" />
					</folder>
				</folder>
				<folder name="lib">
					<folder name="exceptions">
						<file name="ImageNotFoundException.class" />
						<file name="ImagePathNotValidException.class" />
						<file name="InvalidArrayFormatException.class" />
						<file name="InvalidImageDataException.class" />
						<file name="InvalidImageFormatException.class" />
						<file name="InvalidPhotoAlbumNameException.class" />
						<file name="PersistenceMechanismException.class" />
						<file name="UnavailablePhotoAlbumException.class" />
					</folder>
				</folder>
				<folder name="sms">
					<file name=".dircolors" />
					<file name="NetworkScreen.class" />
					<file name="SmsMessaging.class" />
					<file name="SmsReceiverController.class" />
					<file name="SmsReceiverThread.class" />
					<file name="SmsSenderController.class" />
					<file name="SmsSenderThread.class" />
				</folder>
			</folder>
		</folder>
	</folder>
	<file name="build.xml" />
	<folder name="images">
		<file name="Duke1.PNG" />
		<file name="Gail1.PNG" />
		<file name="Gosling1.PNG" />
		<file name="Gregor1.PNG" />
		<file name="Java.png" />
		<file name="Kdvolder1.PNG" />
		<file name="Penguin.png" />
		<file name="Thumbs.db" />
		<file name="Tucan.png" />
		<file name="applause.wav" />
		<file name="baby.wav" />
		<file name="bong.wav" />
		<file name="cabeza.mid" />
		<file name="fish.mpg" />
		<file name="frogs.mp3" />
		<file name="jump.wav" />
		<file name="laughter.wav" />
		<file name="printer.wav" />
		<file name="sydharbour.mp4" />
		<file name="ubcLogo.PNG" />
	</folder>
	<folder name="jars">
		<file name="MobileMedia.jad" />
		<file name="MobileMedia.jar" />
	</folder>
	<file name="labBuild.properties" />
	<file name="model.colors" />
	<file name="model.m" />
	<file name="observations.txt" />
	<folder name="preverified">
		<folder name="images">
			<file name="Duke1.PNG" />
			<file name="Gail1.PNG" />
			<file name="Gosling1.PNG" />
			<file name="Gregor1.PNG" />
			<file name="Java.png" />
			<file name="Kdvolder1.PNG" />
			<file name="Penguin.png" />
			<file name="Thumbs.db" />
			<file name="Tucan.png" />
			<file name="applause.wav" />
			<file name="baby.wav" />
			<file name="bong.wav" />
			<file name="cabeza.mid" />
			<file name="fish.mpg" />
			<file name="frogs.mp3" />
			<file name="jump.wav" />
			<file name="laughter.wav" />
			<file name="printer.wav" />
			<file name="sydharbour.mp4" />
			<file name="ubcLogo.PNG" />
		</folder>
	</folder>
	<folder name="src">
		<file name="LocMetrics.css" />
		<file name="LocMetrics.html" />
		<file name="LocMetricsCommentWords.csv" />
		<file name="LocMetricsFiles.csv" />
		<file name="LocMetricsFolders.csv" />
		<file name="LocMetricsPie.jpg" />
		<file name="LocMetricsPie.png" />
		<folder name="lancs">
			<folder name="mobilemedia">
				<folder name="core">
					<folder name="comms">
						<file name="BaseMessaging.java" />
					</folder>
					<folder name="threads">
						<file name="BaseThread.java" />
					</folder>
					<folder name="ui">
						<file name="MainUIMidlet.java">
							<fragment length="58" offset="550">
								<feature>includeVideo</feature>
							</fragment>
							<fragment length="58" offset="681">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="58" offset="807">
								<feature>includeMMAPI</feature>
							</fragment>
							<fragment length="66" offset="1083">
								<feature>x_misc</feature>
							</fragment>
							<fragment length="59" offset="1151">
								<feature>x_misc</feature>
							</fragment>
							<fragment length="51" offset="1252">
								<feature>includeSmsFeature</feature>
							</fragment>
							<fragment length="47" offset="1305">
								<feature>includeSmsFeature</feature>
							</fragment>
							<fragment length="43" offset="2391">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="29" offset="2437">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="43" offset="2542">
								<feature>includeMMAPI</feature>
							</fragment>
							<fragment length="29" offset="2588">
								<feature>includeMMAPI</feature>
							</fragment>
							<fragment length="43" offset="2693">
								<feature>includeVideo</feature>
							</fragment>
							<fragment length="29" offset="2739">
								<feature>includeVideo</feature>
							</fragment>
							<fragment length="34" offset="3114">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="46" offset="3154">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="66" offset="3204">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="91" offset="3342">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="59" offset="3437">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="79" offset="3504">
								<feature>includePhotoAlbum</feature>
							</fragment>
							<fragment length="55" offset="3587">
